### ISSUE TITLE
 Dynamic HTML content

### ISSUE THREAD

**Issue by kukac7** [ryangjchandler/alpine-tooltip#27]
hi,

i want to display data from a distant parent scope with my own html code in the tooltip.

e.g. similarly.

```
<div x-data="{ tooltip: 'This is crazy!' }">

    <button x-tooltip="{ content: $refs.tooltipHtml.innerHTML, allowHTML: true }">Hover for info!</button>

    <template x-ref="tooltipHtml">
        <p x-text="tooltip"></p>
    </template>
</div>
```

[demo](https://codepen.io/kukac7/pen/zYpVmZo)

i think the ref due inside the data can't be used.
what is a good way to have your own dynamic html code?

thanks for your help!

**Comment by ryangjchandler** [comment]
@kukac7 Sorry for the delay on this issue. There's a couple of nuances with how Tippy handles dynamic HTML content.

Your current code will only provide the tooltip HTML once (not each time is shows and hides). You'll want to update your code to something like this CodePen: https://codepen.io/ryangjchandler/pen/gOvxvPJ

Here's a list of changes:
1. The `content` property can accept a callback function that returns a string. This will get called each time Tippy goes to show the tooltip so that content can be dynamic at point of display instead of initialisation.
2. By default, Tippy will add the actual tooltip element to the end of the `<body>`. In your case, this is outside of the Alpine component so data binding and other Alpine directives won't work. We need to tell Tippy to append it to the `$root` (the element with `x-data` or `x-init`) so that Alpine is able to resolve data etc.

I'm going to update the docs with an example so that others don't run into the same problem. Hope this helps!

**Comment by kukac7** [comment]
hi @ryangjchandler 

thanks for the help!

i forgot an info. 😄 
i want to display your `x-for` data in a tooltip.
this is not possible with your method either.
how could this be solved?

[demo](https://codepen.io/kukac7/pen/BaYwqyb)

thanks!

**Comment by ryangjchandler** [comment]
@kukac7 I don't think this is going to be possible. The `x-for` relies on data only available inside of the `x-for`. There's a potential that using `Alpine.mutateDom()` could help, since Alpine won't try to evaluate directives but I don't think Tippy will work then because it doesn't do everything in one step (to my knowledge).

**Comment by tcyrus** [comment]
I was able to get this working by changing the `$root` and using `x-id` instead of `x-ref`

```html
<div x-data="{ content: [1,2,3,4] }">
  <template x-for="item in content">
    <div x-data="{ item }" x-id="['tooltip']">
      <template :id="$id('tooltip')">
        <p x-text="item"></p>
      </template>
        <button x-tooltip="{ content: () => document.getElementById($id('tooltip')).innerHTML, allowHTML: true, appendTo: $root }">
            Hover for info!
        </button>
    </div> 
  </template>
</div>
```

It would be neat if there was a way to overload `setContent` so that you could use `x-teleport`
https://github.com/atomiks/tippyjs/blob/ad85f6feb79cf6c5853c43bf1b2a50c4fa98e7a1/src/template.ts#L38-L49
