### ISSUE TITLE
Tippy dependency confusion

### ISSUE THREAD

**Issue by browner12** [ryangjchandler/alpine-tooltip#38]
I'm a little confused how the TippyJS dependency works for this package. Shouldn't `tippy.js` be in the `dependencies`, rather than the `devDependencies` of the `package.json` file?  Somehow the plugin still works even without this. Are you compiling/including the entirety of Tippy in this repo in order to use it?   If this is the case, doesn't this make us dependent on this package re-compiling if Tippy makes updates, rather than getting them ourselves?

I also found myself directly requiring the Tippy package anyway, in order to compile the necessary CSS into my app.

**Comment by ryangjchandler** [comment]
Yeah this is a good question. 

It should really be moved to a dependency rather than a dev dependency, yes. The `main` entry in the package.json file should also be updated to point to the src files rather than the dist ones so that users compiling themselves can do it from raw source rather than pre-compiled.

**Comment by browner12** [comment]
Thanks for the response. I'm willing to help out where I can, but it sounds like maybe you have some thoughts for a slightly larger adjustment?

**Comment by ryangjchandler** [comment]
These changes have been made.

Tippy.js is now a dependency on this package, the `main` entry also points to the raw source code to allow compilation with source & accompanying dependencies rather than compilation of the bundled unit.

**Comment by browner12** [comment]
thanks for this!
